-- Migration 087: Per-candidate onboarding token.
--
-- Each candidate gets a unique URL they can use to complete their
-- onboarding without an admin login:
--   /recruitment-onboarding/<token>
--
-- The token is the only auth needed to read/update that candidate's
-- onboarding stages from the public endpoint, so it must be high-entropy
-- and unguessable. Generated by the PHP create handler with random_bytes()
-- and lifted via bin2hex().
--
-- Existing rows are backfilled with a one-time random token so HR can
-- generate the link for any candidate already on the books.

USE `builtrightstudio_cms`;

ALTER TABLE `recruitment_candidates`
  ADD COLUMN `onboarding_token` VARCHAR(64) NULL AFTER `notes`,
  ADD UNIQUE KEY `uniq_onboarding_token` (`onboarding_token`);

-- Backfill: a deterministic-but-unguessable token derived from a random
-- UUID per row. RAND()-based to stay portable across MariaDB versions.
UPDATE `recruitment_candidates`
   SET `onboarding_token` = LOWER(REPLACE(UUID(), '-', ''))
 WHERE `onboarding_token` IS NULL;
