<?php
declare(strict_types=1);

/**
 * One-shot generator for the migration 102-107 tenant_id ALTERs.
 *
 * The pattern is mechanical (ADD COLUMN NULL → backfill 1 → MODIFY NOT
 * NULL + FK + index) so authoring 100 of them by hand is error-prone.
 * This script emits the SQL files using a single template per table.
 *
 * Re-run safe: it overwrites the existing migration files in-place. If
 * a new tenant-scoped table is added later, append it to the GROUPS
 * map below + bump the relevant migration number — the regenerated
 * file will pick it up.
 *
 * Usage:
 *   php cms/scripts/gen-tenant-id-migrations.php
 *
 * Writes:
 *   cms/db/migrations/102_tenant_id_hr_employee_side.sql
 *   cms/db/migrations/103_tenant_id_hr_recruiting_perf.sql
 *   cms/db/migrations/104_tenant_id_ops_partners.sql
 *   cms/db/migrations/105_tenant_id_recruitment.sql
 *   cms/db/migrations/106_tenant_id_tasks.sql
 *   cms/db/migrations/107_tenant_id_misc.sql
 */

/** Tables grouped by migration. Order within each list controls the
 *  order of ALTERs inside the generated file — doesn't matter
 *  functionally since FK to tenants.id was created in migration 099. */
$GROUPS = [
    [
        'number' => 102,
        'name'   => 'tenant_id_hr_employee_side',
        'title'  => 'HR — employees and adjacent tables',
        'tables' => [
            'hr_employees', 'hr_employee_notes', 'hr_employee_skills', 'hr_employment_history',
            'hr_documents', 'hr_document_types', 'hr_contract_groups',
            'hr_default_onboarding_tasks', 'hr_onboarding_tasks',
            'hr_payroll_periods', 'hr_payslips', 'hr_pto_ledger',
            'hr_time_off_requests', 'hr_shifts',
            'hr_certifications', 'hr_references', 'hr_change_requests',
            'hr_legal_documents', 'hr_feedback', 'hr_feedback_notes',
        ],
    ],
    [
        'number' => 103,
        'name'   => 'tenant_id_hr_recruiting_perf',
        'title'  => 'HR — recruiting, learning, performance',
        'tables' => [
            'hr_jobs', 'hr_candidates', 'hr_applications', 'hr_application_notes', 'hr_interviews',
            'hr_skills', 'hr_goals',
            'hr_courses', 'hr_course_assignments', 'hr_course_modules', 'hr_course_module_progress',
            'hr_compliance_tasks', 'hr_compliance_task_notes',
            'hr_pulse_surveys', 'hr_pulse_responses',
            'hr_reviews', 'hr_review_cycles',
            'hr_succession_plans', 'hr_succession_plan_notes',
            'hr_succession_candidates', 'hr_succession_candidate_notes',
        ],
    ],
    [
        'number' => 104,
        'name'   => 'tenant_id_ops_partners',
        'title'  => 'Operations — tenders, partners, contractors, affiliates',
        'tables' => [
            'tenders', 'tender_contacts', 'tender_contact_numbers',
            'tender_documents', 'tender_document_sections', 'tender_info', 'tender_notes',
            'operation_tasks',
            'partners', 'partner_contacts', 'partner_accounts', 'partner_documents', 'partner_notes',
            'contractors', 'contractor_documents', 'contractor_notes',
            'affiliates', 'affiliate_documents', 'affiliate_notes',
        ],
    ],
    [
        'number' => 105,
        'name'   => 'tenant_id_recruitment',
        'title'  => 'Recruitment + audience-specific document tables',
        'tables' => [
            'recruitment_candidates', 'recruitment_candidate_documents', 'recruitment_candidate_notes',
            'recruitment_doc_groups', 'recruitment_doc_types',
            'recruitment_placements', 'recruitment_roles', 'recruitment_skills',
            'candidate_documents', 'applicant_documents',
        ],
    ],
    [
        'number' => 106,
        'name'   => 'tenant_id_tasks',
        'title'  => 'Tasks system (taskboard + projects + items)',
        'tables' => [
            'task_items', 'task_item_attachments', 'task_item_comments', 'task_item_history',
            'task_item_links', 'task_item_states', 'task_item_tags', 'task_item_types',
            'task_iterations', 'task_projects', 'task_sprint_capacity',
            'task_tags', 'task_teams', 'task_team_members',
        ],
    ],
    [
        'number' => 107,
        'name'   => 'tenant_id_misc',
        'title'  => 'Misc — newsletter, billing, contract types, AI models',
        'tables' => [
            'newsletter_campaigns', 'newsletter_recipients', 'newsletter_suppressions',
            'invoices', 'invoice_lines',
            'contract_types', 'ai_models',
        ],
    ],
];

$header = function (int $number, string $title, array $tables): string {
    $count = count($tables);
    return <<<SQL
-- Migration {$number}: tenant_id on {$title}.
-- Generated by cms/scripts/gen-tenant-id-migrations.php.
-- {$count} table(s); pattern matches migration 100 (ADD NULL → backfill
-- 1 → NOT NULL + FK + index). See 100's header for design rationale.


SQL;
};

$tableBlock = function (string $t): string {
    // Intentionally NO position clause. The codebase has a handful of
    // junction tables (task_item_tags, task_team_members, newsletter_
    // suppressions, settings) with composite PKs and no `id` column;
    // an `AFTER id` clause would crash with 1054 on those. MySQL appends
    // the column to the end of the row when no position is specified,
    // which is purely aesthetic — SELECT * with explicit columns picks
    // up the value regardless.
    return <<<SQL
ALTER TABLE `{$t}` ADD COLUMN `tenant_id` INT UNSIGNED NULL;
UPDATE      `{$t}` SET    `tenant_id` = 1;
ALTER TABLE `{$t}` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_{$t}_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_{$t}_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);


SQL;
};

$migrationsDir = __DIR__ . '/../db/migrations';

foreach ($GROUPS as $group) {
    $body = $header($group['number'], $group['title'], $group['tables']);
    foreach ($group['tables'] as $table) {
        $body .= $tableBlock($table);
    }
    $filename = sprintf('%s/%03d_%s.sql', $migrationsDir, $group['number'], $group['name']);
    file_put_contents($filename, $body);
    fprintf(STDERR, "wrote %s (%d tables)\n", basename($filename), count($group['tables']));
}

fprintf(STDERR, "Done — %d migration files generated.\n", count($GROUPS));
