<?php
/**
 * UK SIC 2007 (condensed) lookup.
 * code => ['n' => description, 's' => SIC section letter A-U]
 * Keys are 5-digit zero-padded to match Companies House API output.
 */
return [
    '01110' => ['n' => 'Growing of cereals (except rice), leguminous crops and oil seeds', 's' => 'A'],
    '01120' => ['n' => 'Growing of rice', 's' => 'A'],
    '01130' => ['n' => 'Growing of vegetables and melons, roots and tubers', 's' => 'A'],
    '01140' => ['n' => 'Growing of sugar cane', 's' => 'A'],
    '01150' => ['n' => 'Growing of tobacco', 's' => 'A'],
    '01160' => ['n' => 'Growing of fibre crops', 's' => 'A'],
    '01190' => ['n' => 'Growing of other non-perennial crops', 's' => 'A'],
    '01210' => ['n' => 'Growing of grapes', 's' => 'A'],
    '01220' => ['n' => 'Growing of tropical and subtropical fruits', 's' => 'A'],
    '01230' => ['n' => 'Growing of citrus fruits', 's' => 'A'],
    '01240' => ['n' => 'Growing of pome fruits and stone fruits', 's' => 'A'],
    '01250' => ['n' => 'Growing of other tree and bush fruits and nuts', 's' => 'A'],
    '01260' => ['n' => 'Growing of oleaginous fruits', 's' => 'A'],
    '01270' => ['n' => 'Growing of beverage crops', 's' => 'A'],
    '01280' => ['n' => 'Growing of spices, aromatic, drug and pharmaceutical crops', 's' => 'A'],
    '01290' => ['n' => 'Growing of other perennial crops', 's' => 'A'],
    '01300' => ['n' => 'Plant propagation', 's' => 'A'],
    '01410' => ['n' => 'Raising of dairy cattle', 's' => 'A'],
    '01420' => ['n' => 'Raising of other cattle and buffaloes', 's' => 'A'],
    '01430' => ['n' => 'Raising of horses and other equines', 's' => 'A'],
    '01440' => ['n' => 'Raising of camels and camelids', 's' => 'A'],
    '01450' => ['n' => 'Raising of sheep and goats', 's' => 'A'],
    '01460' => ['n' => 'Raising of swine/pigs', 's' => 'A'],
    '01470' => ['n' => 'Raising of poultry', 's' => 'A'],
    '01490' => ['n' => 'Raising of other animals', 's' => 'A'],
    '01500' => ['n' => 'Mixed farming', 's' => 'A'],
    '01610' => ['n' => 'Support activities for crop production', 's' => 'A'],
    '01621' => ['n' => 'Farm animal boarding and care', 's' => 'A'],
    '01629' => ['n' => 'Support activities for animal production (other than farm animal boarding and care) n.e.c.', 's' => 'A'],
    '01630' => ['n' => 'Post-harvest crop activities', 's' => 'A'],
    '01640' => ['n' => 'Seed processing for propagation', 's' => 'A'],
    '01700' => ['n' => 'Hunting, trapping and related service activities', 's' => 'A'],
    '02100' => ['n' => 'Silviculture and other forestry activities', 's' => 'A'],
    '02200' => ['n' => 'Logging', 's' => 'A'],
    '02300' => ['n' => 'Gathering of wild growing non-wood products', 's' => 'A'],
    '02400' => ['n' => 'Support services to forestry', 's' => 'A'],
    '03110' => ['n' => 'Marine fishing', 's' => 'A'],
    '03120' => ['n' => 'Freshwater fishing', 's' => 'A'],
    '03210' => ['n' => 'Marine aquaculture', 's' => 'A'],
    '03220' => ['n' => 'Freshwater aquaculture', 's' => 'A'],
    '05101' => ['n' => 'Deep coal mines', 's' => 'B'],
    '05102' => ['n' => 'Open cast coal working', 's' => 'B'],
    '05200' => ['n' => 'Mining of lignite', 's' => 'B'],
    '06100' => ['n' => 'Extraction of crude petroleum', 's' => 'B'],
    '06200' => ['n' => 'Extraction of natural gas', 's' => 'B'],
    '07100' => ['n' => 'Mining of iron ores', 's' => 'B'],
    '07210' => ['n' => 'Mining of uranium and thorium ores', 's' => 'B'],
    '07290' => ['n' => 'Mining of other non-ferrous metal ores', 's' => 'B'],
    '08110' => ['n' => 'Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate', 's' => 'B'],
    '08120' => ['n' => 'Operation of gravel and sand pits; mining of clays and kaolin', 's' => 'B'],
    '08910' => ['n' => 'Mining of chemical and fertilizer minerals', 's' => 'B'],
    '08920' => ['n' => 'Extraction of peat', 's' => 'B'],
    '08930' => ['n' => 'Extraction of salt', 's' => 'B'],
    '08990' => ['n' => 'Other mining and quarrying n.e.c.', 's' => 'B'],
    '09100' => ['n' => 'Support activities for petroleum and natural gas mining', 's' => 'B'],
    '09900' => ['n' => 'Support activities for other mining and quarrying', 's' => 'B'],
    '10110' => ['n' => 'Processing and preserving of meat', 's' => 'C'],
    '10120' => ['n' => 'Processing and preserving of poultry meat', 's' => 'C'],
    '10130' => ['n' => 'Production of meat and poultry meat products', 's' => 'C'],
    '10200' => ['n' => 'Processing and preserving of fish, crustaceans and molluscs', 's' => 'C'],
    '10310' => ['n' => 'Processing and preserving of potatoes', 's' => 'C'],
    '10320' => ['n' => 'Manufacture of fruit and vegetable juice', 's' => 'C'],
    '10390' => ['n' => 'Other processing and preserving of fruit and vegetables', 's' => 'C'],
    '10410' => ['n' => 'Manufacture of oils and fats', 's' => 'C'],
    '10420' => ['n' => 'Manufacture of margarine and similar edible fats', 's' => 'C'],
    '10511' => ['n' => 'Liquid milk and cream production', 's' => 'C'],
    '10512' => ['n' => 'Butter and cheese production', 's' => 'C'],
    '10519' => ['n' => 'Manufacture of other milk products', 's' => 'C'],
    '10520' => ['n' => 'Manufacture of ice cream', 's' => 'C'],
    '10611' => ['n' => 'Grain milling', 's' => 'C'],
    '10612' => ['n' => 'Manufacture of breakfast cereals and cereals-based food', 's' => 'C'],
    '10620' => ['n' => 'Manufacture of starches and starch products', 's' => 'C'],
    '10710' => ['n' => 'Manufacture of bread; manufacture of fresh pastry goods and cakes', 's' => 'C'],
    '10720' => ['n' => 'Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes', 's' => 'C'],
    '10730' => ['n' => 'Manufacture of macaroni, noodles, couscous and similar farinaceous products', 's' => 'C'],
    '10810' => ['n' => 'Manufacture of sugar', 's' => 'C'],
    '10821' => ['n' => 'Manufacture of cocoa and chocolate confectionery', 's' => 'C'],
    '10822' => ['n' => 'Manufacture of sugar confectionery', 's' => 'C'],
    '10831' => ['n' => 'Tea processing', 's' => 'C'],
    '10832' => ['n' => 'Production of coffee and coffee substitutes', 's' => 'C'],
    '10840' => ['n' => 'Manufacture of condiments and seasonings', 's' => 'C'],
    '10850' => ['n' => 'Manufacture of prepared meals and dishes', 's' => 'C'],
    '10860' => ['n' => 'Manufacture of homogenized food preparations and dietetic food', 's' => 'C'],
    '10890' => ['n' => 'Manufacture of other food products n.e.c.', 's' => 'C'],
    '10910' => ['n' => 'Manufacture of prepared feeds for farm animals', 's' => 'C'],
    '10920' => ['n' => 'Manufacture of prepared pet foods', 's' => 'C'],
    '11010' => ['n' => 'Distilling, rectifying and blending of spirits', 's' => 'C'],
    '11020' => ['n' => 'Manufacture of wine from grape', 's' => 'C'],
    '11030' => ['n' => 'Manufacture of cider and other fruit wines', 's' => 'C'],
    '11040' => ['n' => 'Manufacture of other non-distilled fermented beverages', 's' => 'C'],
    '11050' => ['n' => 'Manufacture of beer', 's' => 'C'],
    '11060' => ['n' => 'Manufacture of malt', 's' => 'C'],
    '11070' => ['n' => 'Manufacture of soft drinks; production of mineral waters and other bottled waters', 's' => 'C'],
    '12000' => ['n' => 'Manufacture of tobacco products', 's' => 'C'],
    '13100' => ['n' => 'Preparation and spinning of textile fibres', 's' => 'C'],
    '13200' => ['n' => 'Weaving of textiles', 's' => 'C'],
    '13300' => ['n' => 'Finishing of textiles', 's' => 'C'],
    '13910' => ['n' => 'Manufacture of knitted and crocheted fabrics', 's' => 'C'],
    '13921' => ['n' => 'Manufacture of soft furnishings', 's' => 'C'],
    '13922' => ['n' => 'Manufacture of canvas goods, sacks, etc.', 's' => 'C'],
    '13923' => ['n' => 'Manufacture of household textiles', 's' => 'C'],
    '13931' => ['n' => 'Manufacture of woven or tufted carpets and rugs', 's' => 'C'],
    '13939' => ['n' => 'Manufacture of other carpets and rugs', 's' => 'C'],
    '13940' => ['n' => 'Manufacture of cordage, rope, twine and netting', 's' => 'C'],
    '13950' => ['n' => 'Manufacture of non-wovens and articles made from non-wovens, except apparel', 's' => 'C'],
    '13960' => ['n' => 'Manufacture of other technical and industrial textiles', 's' => 'C'],
    '13990' => ['n' => 'Manufacture of other textiles n.e.c.', 's' => 'C'],
    '14110' => ['n' => 'Manufacture of leather clothes', 's' => 'C'],
    '14120' => ['n' => 'Manufacture of workwear', 's' => 'C'],
    '14131' => ['n' => 'Manufacture of other men\'s outerwear', 's' => 'C'],
    '14132' => ['n' => 'Manufacture of other women\'s outerwear', 's' => 'C'],
    '14141' => ['n' => 'Manufacture of men\'s underwear', 's' => 'C'],
    '14142' => ['n' => 'Manufacture of women\'s underwear', 's' => 'C'],
    '14190' => ['n' => 'Manufacture of other wearing apparel and accessories n.e.c.', 's' => 'C'],
    '14200' => ['n' => 'Manufacture of articles of fur', 's' => 'C'],
    '14310' => ['n' => 'Manufacture of knitted and crocheted hosiery', 's' => 'C'],
    '14390' => ['n' => 'Manufacture of other knitted and crocheted apparel', 's' => 'C'],
    '15110' => ['n' => 'Tanning and dressing of leather; dressing and dyeing of fur', 's' => 'C'],
    '15120' => ['n' => 'Manufacture of luggage, handbags and the like, saddlery and harness', 's' => 'C'],
    '15200' => ['n' => 'Manufacture of footwear', 's' => 'C'],
    '16100' => ['n' => 'Sawmilling and planing of wood', 's' => 'C'],
    '16210' => ['n' => 'Manufacture of veneer sheets and wood-based panels', 's' => 'C'],
    '16220' => ['n' => 'Manufacture of assembled parquet floors', 's' => 'C'],
    '16230' => ['n' => 'Manufacture of other builders\' carpentry and joinery', 's' => 'C'],
    '16240' => ['n' => 'Manufacture of wooden containers', 's' => 'C'],
    '16290' => ['n' => 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials', 's' => 'C'],
    '17110' => ['n' => 'Manufacture of pulp', 's' => 'C'],
    '17120' => ['n' => 'Manufacture of paper and paperboard', 's' => 'C'],
    '17211' => ['n' => 'Manufacture of corrugated paper and paperboard, sacks and bags', 's' => 'C'],
    '17219' => ['n' => 'Manufacture of other paper and paperboard containers', 's' => 'C'],
    '17220' => ['n' => 'Manufacture of household and sanitary goods and of toilet requisites', 's' => 'C'],
    '17230' => ['n' => 'Manufacture of paper stationery', 's' => 'C'],
    '17240' => ['n' => 'Manufacture of wallpaper', 's' => 'C'],
    '17290' => ['n' => 'Manufacture of other articles of paper and paperboard n.e.c.', 's' => 'C'],
    '18110' => ['n' => 'Printing of newspapers', 's' => 'C'],
    '18121' => ['n' => 'Manufacture of printed labels', 's' => 'C'],
    '18129' => ['n' => 'Printing n.e.c.', 's' => 'C'],
    '18130' => ['n' => 'Pre-press and pre-media services', 's' => 'C'],
    '18140' => ['n' => 'Binding and related services', 's' => 'C'],
    '18201' => ['n' => 'Reproduction of sound recording', 's' => 'C'],
    '18202' => ['n' => 'Reproduction of video recording', 's' => 'C'],
    '18203' => ['n' => 'Reproduction of computer media', 's' => 'C'],
    '19100' => ['n' => 'Manufacture of coke oven products', 's' => 'C'],
    '19201' => ['n' => 'Mineral oil refining', 's' => 'C'],
    '19209' => ['n' => 'Other treatment of petroleum products (excluding petrochemicals manufacture)', 's' => 'C'],
    '20110' => ['n' => 'Manufacture of industrial gases', 's' => 'C'],
    '20120' => ['n' => 'Manufacture of dyes and pigments', 's' => 'C'],
    '20130' => ['n' => 'Manufacture of other inorganic basic chemicals', 's' => 'C'],
    '20140' => ['n' => 'Manufacture of other organic basic chemicals', 's' => 'C'],
    '20150' => ['n' => 'Manufacture of fertilizers and nitrogen compounds', 's' => 'C'],
    '20160' => ['n' => 'Manufacture of plastics in primary forms', 's' => 'C'],
    '20170' => ['n' => 'Manufacture of synthetic rubber in primary forms', 's' => 'C'],
    '20200' => ['n' => 'Manufacture of pesticides and other agrochemical products', 's' => 'C'],
    '20301' => ['n' => 'Manufacture of paints, varnishes and similar coatings, mastics and sealants', 's' => 'C'],
    '20302' => ['n' => 'Manufacture of printing ink', 's' => 'C'],
    '20411' => ['n' => 'Manufacture of soap and detergents', 's' => 'C'],
    '20412' => ['n' => 'Manufacture of cleaning and polishing preparations', 's' => 'C'],
    '20420' => ['n' => 'Manufacture of perfumes and toilet preparations', 's' => 'C'],
    '20510' => ['n' => 'Manufacture of explosives', 's' => 'C'],
    '20520' => ['n' => 'Manufacture of glues', 's' => 'C'],
    '20530' => ['n' => 'Manufacture of essential oils', 's' => 'C'],
    '20590' => ['n' => 'Manufacture of other chemical products n.e.c.', 's' => 'C'],
    '20600' => ['n' => 'Manufacture of man-made fibres', 's' => 'C'],
    '21100' => ['n' => 'Manufacture of basic pharmaceutical products', 's' => 'C'],
    '21200' => ['n' => 'Manufacture of pharmaceutical preparations', 's' => 'C'],
    '22110' => ['n' => 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres', 's' => 'C'],
    '22190' => ['n' => 'Manufacture of other rubber products', 's' => 'C'],
    '22210' => ['n' => 'Manufacture of plastic plates, sheets, tubes and profiles', 's' => 'C'],
    '22220' => ['n' => 'Manufacture of plastic packing goods', 's' => 'C'],
    '22230' => ['n' => 'Manufacture of builders ware of plastic', 's' => 'C'],
    '22290' => ['n' => 'Manufacture of other plastic products', 's' => 'C'],
    '23110' => ['n' => 'Manufacture of flat glass', 's' => 'C'],
    '23120' => ['n' => 'Shaping and processing of flat glass', 's' => 'C'],
    '23130' => ['n' => 'Manufacture of hollow glass', 's' => 'C'],
    '23140' => ['n' => 'Manufacture of glass fibres', 's' => 'C'],
    '23190' => ['n' => 'Manufacture and processing of other glass, including technical glassware', 's' => 'C'],
    '23200' => ['n' => 'Manufacture of refractory products', 's' => 'C'],
    '23310' => ['n' => 'Manufacture of ceramic tiles and flags', 's' => 'C'],
    '23320' => ['n' => 'Manufacture of bricks, tiles and construction products, in baked clay', 's' => 'C'],
    '23410' => ['n' => 'Manufacture of ceramic household and ornamental articles', 's' => 'C'],
    '23420' => ['n' => 'Manufacture of ceramic sanitary fixtures', 's' => 'C'],
    '23430' => ['n' => 'Manufacture of ceramic insulators and insulating fittings', 's' => 'C'],
    '23440' => ['n' => 'Manufacture of other technical ceramic products', 's' => 'C'],
    '23490' => ['n' => 'Manufacture of other ceramic products n.e.c.', 's' => 'C'],
    '23510' => ['n' => 'Manufacture of cement', 's' => 'C'],
    '23520' => ['n' => 'Manufacture of lime and plaster', 's' => 'C'],
    '23610' => ['n' => 'Manufacture of concrete products for construction purposes', 's' => 'C'],
    '23620' => ['n' => 'Manufacture of plaster products for construction purposes', 's' => 'C'],
    '23630' => ['n' => 'Manufacture of ready-mixed concrete', 's' => 'C'],
    '23640' => ['n' => 'Manufacture of mortars', 's' => 'C'],
    '23650' => ['n' => 'Manufacture of fibre cement', 's' => 'C'],
    '23690' => ['n' => 'Manufacture of other articles of concrete, plaster and cement', 's' => 'C'],
    '23700' => ['n' => 'Cutting, shaping and finishing of stone', 's' => 'C'],
    '23910' => ['n' => 'Production of abrasive products', 's' => 'C'],
    '23990' => ['n' => 'Manufacture of other non-metallic mineral products n.e.c.', 's' => 'C'],
    '24100' => ['n' => 'Manufacture of basic iron and steel and of ferro-alloys', 's' => 'C'],
    '24200' => ['n' => 'Manufacture of tubes, pipes, hollow profiles and related fittings, of steel', 's' => 'C'],
    '24310' => ['n' => 'Cold drawing of bars', 's' => 'C'],
    '24320' => ['n' => 'Cold rolling of narrow strip', 's' => 'C'],
    '24330' => ['n' => 'Cold forming or folding', 's' => 'C'],
    '24340' => ['n' => 'Cold drawing of wire', 's' => 'C'],
    '24410' => ['n' => 'Precious metals production', 's' => 'C'],
    '24420' => ['n' => 'Aluminium production', 's' => 'C'],
    '24430' => ['n' => 'Lead, zinc and tin production', 's' => 'C'],
    '24440' => ['n' => 'Copper production', 's' => 'C'],
    '24450' => ['n' => 'Other non-ferrous metal production', 's' => 'C'],
    '24460' => ['n' => 'Processing of nuclear fuel', 's' => 'C'],
    '24510' => ['n' => 'Casting of iron', 's' => 'C'],
    '24520' => ['n' => 'Casting of steel', 's' => 'C'],
    '24530' => ['n' => 'Casting of light metals', 's' => 'C'],
    '24540' => ['n' => 'Casting of other non-ferrous metals', 's' => 'C'],
    '25110' => ['n' => 'Manufacture of metal structures and parts of structures', 's' => 'C'],
    '25120' => ['n' => 'Manufacture of doors and windows of metal', 's' => 'C'],
    '25210' => ['n' => 'Manufacture of central heating radiators and boilers', 's' => 'C'],
    '25290' => ['n' => 'Manufacture of other tanks, reservoirs and containers of metal', 's' => 'C'],
    '25300' => ['n' => 'Manufacture of steam generators, except central heating hot water boilers', 's' => 'C'],
    '25400' => ['n' => 'Manufacture of weapons and ammunition', 's' => 'C'],
    '25500' => ['n' => 'Forging, pressing, stamping and roll-forming of metal; powder metallurgy', 's' => 'C'],
    '25610' => ['n' => 'Treatment and coating of metals', 's' => 'C'],
    '25620' => ['n' => 'Machining', 's' => 'C'],
    '25710' => ['n' => 'Manufacture of cutlery', 's' => 'C'],
    '25720' => ['n' => 'Manufacture of locks and hinges', 's' => 'C'],
    '25730' => ['n' => 'Manufacture of tools', 's' => 'C'],
    '25910' => ['n' => 'Manufacture of steel drums and similar containers', 's' => 'C'],
    '25920' => ['n' => 'Manufacture of light metal packaging', 's' => 'C'],
    '25930' => ['n' => 'Manufacture of wire products, chain and springs', 's' => 'C'],
    '25940' => ['n' => 'Manufacture of fasteners and screw machine products', 's' => 'C'],
    '25990' => ['n' => 'Manufacture of other fabricated metal products n.e.c.', 's' => 'C'],
    '26110' => ['n' => 'Manufacture of electronic components', 's' => 'C'],
    '26120' => ['n' => 'Manufacture of loaded electronic boards', 's' => 'C'],
    '26200' => ['n' => 'Manufacture of computers and peripheral equipment', 's' => 'C'],
    '26301' => ['n' => 'Manufacture of telegraph and telephone apparatus and equipment', 's' => 'C'],
    '26309' => ['n' => 'Manufacture of communication equipment other than telegraph, and telephone apparatus and equipment', 's' => 'C'],
    '26400' => ['n' => 'Manufacture of consumer electronics', 's' => 'C'],
    '26511' => ['n' => 'Manufacture of electronic measuring, testing etc. equipment, not for industrial process control', 's' => 'C'],
    '26512' => ['n' => 'Manufacture of electronic industrial process control equipment', 's' => 'C'],
    '26513' => ['n' => 'Manufacture of non-electronic measuring, testing etc. equipment, not for industrial process control', 's' => 'C'],
    '26514' => ['n' => 'Manufacture of non-electronic industrial process control equipment', 's' => 'C'],
    '26520' => ['n' => 'Manufacture of watches and clocks', 's' => 'C'],
    '26600' => ['n' => 'Manufacture of irradiation, electromedical and electrotherapeutic equipment', 's' => 'C'],
    '26701' => ['n' => 'Manufacture of optical precision instruments', 's' => 'C'],
    '26702' => ['n' => 'Manufacture of photographic and cinematographic equipment', 's' => 'C'],
    '26800' => ['n' => 'Manufacture of magnetic and optical media', 's' => 'C'],
    '27110' => ['n' => 'Manufacture of electric motors, generators and transformers', 's' => 'C'],
    '27120' => ['n' => 'Manufacture of electricity distribution and control apparatus', 's' => 'C'],
    '27200' => ['n' => 'Manufacture of batteries and accumulators', 's' => 'C'],
    '27310' => ['n' => 'Manufacture of fibre optic cables', 's' => 'C'],
    '27320' => ['n' => 'Manufacture of other electronic and electric wires and cables', 's' => 'C'],
    '27330' => ['n' => 'Manufacture of wiring devices', 's' => 'C'],
    '27400' => ['n' => 'Manufacture of electric lighting equipment', 's' => 'C'],
    '27510' => ['n' => 'Manufacture of electric domestic appliances', 's' => 'C'],
    '27520' => ['n' => 'Manufacture of non-electric domestic appliances', 's' => 'C'],
    '27900' => ['n' => 'Manufacture of other electrical equipment', 's' => 'C'],
    '28110' => ['n' => 'Manufacture of engines and turbines, except aircraft, vehicle and cycle engines', 's' => 'C'],
    '28120' => ['n' => 'Manufacture of fluid power equipment', 's' => 'C'],
    '28131' => ['n' => 'Manufacture of pumps', 's' => 'C'],
    '28132' => ['n' => 'Manufacture of compressors', 's' => 'C'],
    '28140' => ['n' => 'Manufacture of taps and valves', 's' => 'C'],
    '28150' => ['n' => 'Manufacture of bearings, gears, gearing and driving elements', 's' => 'C'],
    '28210' => ['n' => 'Manufacture of ovens, furnaces and furnace burners', 's' => 'C'],
    '28220' => ['n' => 'Manufacture of lifting and handling equipment', 's' => 'C'],
    '28230' => ['n' => 'Manufacture of office machinery and equipment (except computers and peripheral equipment)', 's' => 'C'],
    '28240' => ['n' => 'Manufacture of power-driven hand tools', 's' => 'C'],
    '28250' => ['n' => 'Manufacture of non-domestic cooling and ventilation equipment', 's' => 'C'],
    '28290' => ['n' => 'Manufacture of other general-purpose machinery n.e.c.', 's' => 'C'],
    '28301' => ['n' => 'Manufacture of agricultural tractors', 's' => 'C'],
    '28302' => ['n' => 'Manufacture of agricultural and forestry machinery other than tractors', 's' => 'C'],
    '28410' => ['n' => 'Manufacture of metal forming machinery', 's' => 'C'],
    '28490' => ['n' => 'Manufacture of other machine tools', 's' => 'C'],
    '28910' => ['n' => 'Manufacture of machinery for metallurgy', 's' => 'C'],
    '28921' => ['n' => 'Manufacture of machinery for mining', 's' => 'C'],
    '28922' => ['n' => 'Manufacture of earthmoving equipment', 's' => 'C'],
    '28923' => ['n' => 'Manufacture of equipment for concrete crushing and screening and roadworks', 's' => 'C'],
    '28930' => ['n' => 'Manufacture of machinery for food, beverage and tobacco processing', 's' => 'C'],
    '28940' => ['n' => 'Manufacture of machinery for textile, apparel and leather production', 's' => 'C'],
    '28950' => ['n' => 'Manufacture of machinery for paper and paperboard production', 's' => 'C'],
    '28960' => ['n' => 'Manufacture of plastics and rubber machinery', 's' => 'C'],
    '28990' => ['n' => 'Manufacture of other special-purpose machinery n.e.c.', 's' => 'C'],
    '29100' => ['n' => 'Manufacture of motor vehicles', 's' => 'C'],
    '29201' => ['n' => 'Manufacture of bodies (coachwork) for motor vehicles (except caravans)', 's' => 'C'],
    '29202' => ['n' => 'Manufacture of trailers and semi-trailers', 's' => 'C'],
    '29203' => ['n' => 'Manufacture of caravans', 's' => 'C'],
    '29310' => ['n' => 'Manufacture of electrical and electronic equipment for motor vehicles and their engines', 's' => 'C'],
    '29320' => ['n' => 'Manufacture of other parts and accessories for motor vehicles', 's' => 'C'],
    '30110' => ['n' => 'Building of ships and floating structures', 's' => 'C'],
    '30120' => ['n' => 'Building of pleasure and sporting boats', 's' => 'C'],
    '30200' => ['n' => 'Manufacture of railway locomotives and rolling stock', 's' => 'C'],
    '30300' => ['n' => 'Manufacture of air and spacecraft and related machinery', 's' => 'C'],
    '30400' => ['n' => 'Manufacture of military fighting vehicles', 's' => 'C'],
    '30910' => ['n' => 'Manufacture of motorcycles', 's' => 'C'],
    '30920' => ['n' => 'Manufacture of bicycles and invalid carriages', 's' => 'C'],
    '30990' => ['n' => 'Manufacture of other transport equipment n.e.c.', 's' => 'C'],
    '31010' => ['n' => 'Manufacture of office and shop furniture', 's' => 'C'],
    '31020' => ['n' => 'Manufacture of kitchen furniture', 's' => 'C'],
    '31030' => ['n' => 'Manufacture of mattresses', 's' => 'C'],
    '31090' => ['n' => 'Manufacture of other furniture', 's' => 'C'],
    '32110' => ['n' => 'Striking of coins', 's' => 'C'],
    '32120' => ['n' => 'Manufacture of jewellery and related articles', 's' => 'C'],
    '32130' => ['n' => 'Manufacture of imitation jewellery and related articles', 's' => 'C'],
    '32200' => ['n' => 'Manufacture of musical instruments', 's' => 'C'],
    '32300' => ['n' => 'Manufacture of sports goods', 's' => 'C'],
    '32401' => ['n' => 'Manufacture of professional and arcade games and toys', 's' => 'C'],
    '32409' => ['n' => 'Manufacture of other games and toys, n.e.c.', 's' => 'C'],
    '32500' => ['n' => 'Manufacture of medical and dental instruments and supplies', 's' => 'C'],
    '32910' => ['n' => 'Manufacture of brooms and brushes', 's' => 'C'],
    '32990' => ['n' => 'Other manufacturing n.e.c.', 's' => 'C'],
    '33110' => ['n' => 'Repair of fabricated metal products', 's' => 'C'],
    '33120' => ['n' => 'Repair of machinery', 's' => 'C'],
    '33130' => ['n' => 'Repair of electronic and optical equipment', 's' => 'C'],
    '33140' => ['n' => 'Repair of electrical equipment', 's' => 'C'],
    '33150' => ['n' => 'Repair and maintenance of ships and boats', 's' => 'C'],
    '33160' => ['n' => 'Repair and maintenance of aircraft and spacecraft', 's' => 'C'],
    '33170' => ['n' => 'Repair and maintenance of other transport equipment n.e.c.', 's' => 'C'],
    '33190' => ['n' => 'Repair of other equipment', 's' => 'C'],
    '33200' => ['n' => 'Installation of industrial machinery and equipment', 's' => 'C'],
    '35110' => ['n' => 'Production of electricity', 's' => 'D'],
    '35120' => ['n' => 'Transmission of electricity', 's' => 'D'],
    '35130' => ['n' => 'Distribution of electricity', 's' => 'D'],
    '35140' => ['n' => 'Trade of electricity', 's' => 'D'],
    '35210' => ['n' => 'Manufacture of gas', 's' => 'D'],
    '35220' => ['n' => 'Distribution of gaseous fuels through mains', 's' => 'D'],
    '35230' => ['n' => 'Trade of gas through mains', 's' => 'D'],
    '35300' => ['n' => 'Steam and air conditioning supply remediation activities', 's' => 'D'],
    '36000' => ['n' => 'Water collection, treatment and supply', 's' => 'E'],
    '37000' => ['n' => 'Sewerage', 's' => 'E'],
    '38110' => ['n' => 'Collection of non-hazardous waste', 's' => 'E'],
    '38120' => ['n' => 'Collection of hazardous waste', 's' => 'E'],
    '38210' => ['n' => 'Treatment and disposal of non-hazardous waste', 's' => 'E'],
    '38220' => ['n' => 'Treatment and disposal of hazardous waste', 's' => 'E'],
    '38310' => ['n' => 'Dismantling of wrecks', 's' => 'E'],
    '38320' => ['n' => 'Recovery of sorted materials', 's' => 'E'],
    '39000' => ['n' => 'Remediation activities and other waste management services', 's' => 'E'],
    '41100' => ['n' => 'Development of building projects', 's' => 'F'],
    '41201' => ['n' => 'Construction of commercial buildings', 's' => 'F'],
    '41202' => ['n' => 'Construction of domestic buildings', 's' => 'F'],
    '42110' => ['n' => 'Construction of roads and motorways', 's' => 'F'],
    '42120' => ['n' => 'Construction of railways and underground railways', 's' => 'F'],
    '42130' => ['n' => 'Construction of bridges and tunnels', 's' => 'F'],
    '42210' => ['n' => 'Construction of utility projects for fluids', 's' => 'F'],
    '42220' => ['n' => 'Construction of utility projects for electricity and telecommunications', 's' => 'F'],
    '42910' => ['n' => 'Construction of water projects', 's' => 'F'],
    '42990' => ['n' => 'Construction of other civil engineering projects n.e.c.', 's' => 'F'],
    '43110' => ['n' => 'Demolition', 's' => 'F'],
    '43120' => ['n' => 'Site preparation', 's' => 'F'],
    '43130' => ['n' => 'Test drilling and boring', 's' => 'F'],
    '43210' => ['n' => 'Electrical installation', 's' => 'F'],
    '43220' => ['n' => 'Plumbing, heat and air-conditioning installation', 's' => 'F'],
    '43290' => ['n' => 'Other construction installation', 's' => 'F'],
    '43310' => ['n' => 'Plastering', 's' => 'F'],
    '43320' => ['n' => 'Joinery installation', 's' => 'F'],
    '43330' => ['n' => 'Floor and wall covering', 's' => 'F'],
    '43341' => ['n' => 'Painting', 's' => 'F'],
    '43342' => ['n' => 'Glazing', 's' => 'F'],
    '43390' => ['n' => 'Other building completion and finishing', 's' => 'F'],
    '43910' => ['n' => 'Roofing activities', 's' => 'F'],
    '43991' => ['n' => 'Scaffold erection', 's' => 'F'],
    '43999' => ['n' => 'Other specialised construction activities n.e.c. motorcycles', 's' => 'F'],
    '45111' => ['n' => 'Sale of new cars and light motor vehicles', 's' => 'G'],
    '45112' => ['n' => 'Sale of used cars and light motor vehicles', 's' => 'G'],
    '45190' => ['n' => 'Sale of other motor vehicles', 's' => 'G'],
    '45200' => ['n' => 'Maintenance and repair of motor vehicles', 's' => 'G'],
    '45310' => ['n' => 'Wholesale trade of motor vehicle parts and accessories', 's' => 'G'],
    '45320' => ['n' => 'Retail trade of motor vehicle parts and accessories', 's' => 'G'],
    '45400' => ['n' => 'Sale, maintenance and repair of motorcycles and related parts and accessories', 's' => 'G'],
    '46110' => ['n' => 'Agents selling agricultural raw materials, livestock, textile raw materials and semi-finished goods', 's' => 'G'],
    '46120' => ['n' => 'Agents involved in the sale of fuels, ores, metals and industrial chemicals', 's' => 'G'],
    '46130' => ['n' => 'Agents involved in the sale of timber and building materials', 's' => 'G'],
    '46140' => ['n' => 'Agents involved in the sale of machinery, industrial equipment, ships and aircraft', 's' => 'G'],
    '46150' => ['n' => 'Agents involved in the sale of furniture, household goods, hardware and ironmongery', 's' => 'G'],
    '46160' => ['n' => 'Agents involved in the sale of textiles, clothing, fur, footwear and leather goods', 's' => 'G'],
    '46170' => ['n' => 'Agents involved in the sale of food, beverages and tobacco', 's' => 'G'],
    '46180' => ['n' => 'Agents specialised in the sale of other particular products', 's' => 'G'],
    '46190' => ['n' => 'Agents involved in the sale of a variety of goods', 's' => 'G'],
    '46210' => ['n' => 'Wholesale of grain, unmanufactured tobacco, seeds and animal feeds', 's' => 'G'],
    '46220' => ['n' => 'Wholesale of flowers and plants', 's' => 'G'],
    '46230' => ['n' => 'Wholesale of live animals', 's' => 'G'],
    '46240' => ['n' => 'Wholesale of hides, skins and leather', 's' => 'G'],
    '46310' => ['n' => 'Wholesale of fruit and vegetables', 's' => 'G'],
    '46320' => ['n' => 'Wholesale of meat and meat products', 's' => 'G'],
    '46330' => ['n' => 'Wholesale of dairy products, eggs and edible oils and fats', 's' => 'G'],
    '46341' => ['n' => 'Wholesale of fruit and vegetable juices, mineral water and soft drinks', 's' => 'G'],
    '46342' => ['n' => 'Wholesale of wine, beer, spirits and other alcoholic beverages', 's' => 'G'],
    '46350' => ['n' => 'Wholesale of tobacco products', 's' => 'G'],
    '46360' => ['n' => 'Wholesale of sugar and chocolate and sugar confectionery', 's' => 'G'],
    '46370' => ['n' => 'Wholesale of coffee, tea, cocoa and spices', 's' => 'G'],
    '46380' => ['n' => 'Wholesale of other food, including fish, crustaceans and molluscs', 's' => 'G'],
    '46390' => ['n' => 'Non-specialised wholesale of food, beverages and tobacco', 's' => 'G'],
    '46410' => ['n' => 'Wholesale of textiles', 's' => 'G'],
    '46420' => ['n' => 'Wholesale of clothing and footwear', 's' => 'G'],
    '46431' => ['n' => 'Wholesale of audio tapes, records, CDs and video tapes and the equipment on which these are played', 's' => 'G'],
    '46439' => ['n' => 'Wholesale of radio, television goods & electrical household appliances (other than records, tapes, CD\'s & video tapes and the equipment used for playing them)', 's' => 'G'],
    '46440' => ['n' => 'Wholesale of china and glassware and cleaning materials', 's' => 'G'],
    '46450' => ['n' => 'Wholesale of perfume and cosmetics', 's' => 'G'],
    '46460' => ['n' => 'Wholesale of pharmaceutical goods', 's' => 'G'],
    '46470' => ['n' => 'Wholesale of furniture, carpets and lighting equipment', 's' => 'G'],
    '46480' => ['n' => 'Wholesale of watches and jewellery', 's' => 'G'],
    '46491' => ['n' => 'Wholesale of musical instruments', 's' => 'G'],
    '46499' => ['n' => 'Wholesale of household goods (other than musical instruments) n.e.c', 's' => 'G'],
    '46510' => ['n' => 'Wholesale of computers, computer peripheral equipment and software', 's' => 'G'],
    '46520' => ['n' => 'Wholesale of electronic and telecommunications equipment and parts', 's' => 'G'],
    '46610' => ['n' => 'Wholesale of agricultural machinery, equipment and supplies', 's' => 'G'],
    '46620' => ['n' => 'Wholesale of machine tools', 's' => 'G'],
    '46630' => ['n' => 'Wholesale of mining, construction and civil engineering machinery', 's' => 'G'],
    '46640' => ['n' => 'Wholesale of machinery for the textile industry and of sewing and knitting machines', 's' => 'G'],
    '46650' => ['n' => 'Wholesale of office furniture', 's' => 'G'],
    '46660' => ['n' => 'Wholesale of other office machinery and equipment', 's' => 'G'],
    '46690' => ['n' => 'Wholesale of other machinery and equipment', 's' => 'G'],
    '46711' => ['n' => 'Wholesale of petroleum and petroleum products', 's' => 'G'],
    '46719' => ['n' => 'Wholesale of other fuels and related products', 's' => 'G'],
    '46720' => ['n' => 'Wholesale of metals and metal ores', 's' => 'G'],
    '46730' => ['n' => 'Wholesale of wood, construction materials and sanitary equipment', 's' => 'G'],
    '46740' => ['n' => 'Wholesale of hardware, plumbing and heating equipment and supplies', 's' => 'G'],
    '46750' => ['n' => 'Wholesale of chemical products', 's' => 'G'],
    '46760' => ['n' => 'Wholesale of other intermediate products', 's' => 'G'],
    '46770' => ['n' => 'Wholesale of waste and scrap', 's' => 'G'],
    '46900' => ['n' => 'Non-specialised wholesale trade', 's' => 'G'],
    '47110' => ['n' => 'Retail sale in non-specialised stores with food, beverages or tobacco predominating', 's' => 'G'],
    '47190' => ['n' => 'Other retail sale in non-specialised stores', 's' => 'G'],
    '47210' => ['n' => 'Retail sale of fruit and vegetables in specialised stores', 's' => 'G'],
    '47220' => ['n' => 'Retail sale of meat and meat products in specialised stores', 's' => 'G'],
    '47230' => ['n' => 'Retail sale of fish, crustaceans and molluscs in specialised stores', 's' => 'G'],
    '47240' => ['n' => 'Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores', 's' => 'G'],
    '47250' => ['n' => 'Retail sale of beverages in specialised stores', 's' => 'G'],
    '47260' => ['n' => 'Retail sale of tobacco products in specialised stores', 's' => 'G'],
    '47290' => ['n' => 'Other retail sale of food in specialised stores', 's' => 'G'],
    '47300' => ['n' => 'Retail sale of automotive fuel in specialised stores', 's' => 'G'],
    '47410' => ['n' => 'Retail sale of computers, peripheral units and software in specialised stores', 's' => 'G'],
    '47421' => ['n' => 'Retail sale of mobile telephones', 's' => 'G'],
    '47429' => ['n' => 'Retail sale of telecommunications equipment other than mobile telephones', 's' => 'G'],
    '47430' => ['n' => 'Retail sale of audio and video equipment in specialised stores', 's' => 'G'],
    '47510' => ['n' => 'Retail sale of textiles in specialised stores', 's' => 'G'],
    '47520' => ['n' => 'Retail sale of hardware, paints and glass in specialised stores', 's' => 'G'],
    '47530' => ['n' => 'Retail sale of carpets, rugs, wall and floor coverings in specialised stores', 's' => 'G'],
    '47540' => ['n' => 'Retail sale of electrical household appliances in specialised stores', 's' => 'G'],
    '47591' => ['n' => 'Retail sale of musical instruments and scores', 's' => 'G'],
    '47599' => ['n' => 'Retail of furniture, lighting, and similar (not musical instruments or scores) in specialised store', 's' => 'G'],
    '47610' => ['n' => 'Retail sale of books in specialised stores', 's' => 'G'],
    '47620' => ['n' => 'Retail sale of newspapers and stationery in specialised stores', 's' => 'G'],
    '47630' => ['n' => 'Retail sale of music and video recordings in specialised stores', 's' => 'G'],
    '47640' => ['n' => 'Retail sale of sports goods, fishing gear, camping goods, boats and bicycles', 's' => 'G'],
    '47650' => ['n' => 'Retail sale of games and toys in specialised stores', 's' => 'G'],
    '47710' => ['n' => 'Retail sale of clothing in specialised stores', 's' => 'G'],
    '47721' => ['n' => 'Retail sale of footwear in specialised stores', 's' => 'G'],
    '47722' => ['n' => 'Retail sale of leather goods in specialised stores', 's' => 'G'],
    '47730' => ['n' => 'Dispensing chemist in specialised stores', 's' => 'G'],
    '47741' => ['n' => 'Retail sale of hearing aids', 's' => 'G'],
    '47749' => ['n' => 'Retail sale of medical and orthopaedic goods in specialised stores (not incl. hearing aids) n.e.c.', 's' => 'G'],
    '47750' => ['n' => 'Retail sale of cosmetic and toilet articles in specialised stores', 's' => 'G'],
    '47760' => ['n' => 'Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food in specialised stores', 's' => 'G'],
    '47770' => ['n' => 'Retail sale of watches and jewellery in specialised stores', 's' => 'G'],
    '47781' => ['n' => 'Retail sale in commercial art galleries', 's' => 'G'],
    '47782' => ['n' => 'Retail sale by opticians', 's' => 'G'],
    '47789' => ['n' => 'Other retail sale of new goods in specialised stores (not commercial art galleries and opticians)', 's' => 'G'],
    '47791' => ['n' => 'Retail sale of antiques including antique books in stores', 's' => 'G'],
    '47799' => ['n' => 'Retail sale of other second-hand goods in stores (not incl. antiques)', 's' => 'G'],
    '47810' => ['n' => 'Retail sale via stalls and markets of food, beverages and tobacco products', 's' => 'G'],
    '47820' => ['n' => 'Retail sale via stalls and markets of textiles, clothing and footwear', 's' => 'G'],
    '47890' => ['n' => 'Retail sale via stalls and markets of other goods', 's' => 'G'],
    '47910' => ['n' => 'Retail sale via mail order houses or via Internet', 's' => 'G'],
    '47990' => ['n' => 'Other retail sale not in stores, stalls or markets', 's' => 'G'],
    '49100' => ['n' => 'Passenger rail transport, interurban', 's' => 'H'],
    '49200' => ['n' => 'Freight rail transport', 's' => 'H'],
    '49311' => ['n' => 'Urban and suburban passenger railway transportation by underground, metro and similar systems', 's' => 'H'],
    '49319' => ['n' => 'Other urban, suburban or metropolitan passenger land transport (not underground, metro or similar)', 's' => 'H'],
    '49320' => ['n' => 'Taxi operation', 's' => 'H'],
    '49390' => ['n' => 'Other passenger land transport', 's' => 'H'],
    '49410' => ['n' => 'Freight transport by road', 's' => 'H'],
    '49420' => ['n' => 'Removal services', 's' => 'H'],
    '49500' => ['n' => 'Transport via pipeline', 's' => 'H'],
    '50100' => ['n' => 'Sea and coastal passenger water transport', 's' => 'H'],
    '50200' => ['n' => 'Sea and coastal freight water transport', 's' => 'H'],
    '50300' => ['n' => 'Inland passenger water transport', 's' => 'H'],
    '50400' => ['n' => 'Inland freight water transport', 's' => 'H'],
    '51101' => ['n' => 'Scheduled passenger air transport', 's' => 'H'],
    '51102' => ['n' => 'Non-scheduled passenger air transport', 's' => 'H'],
    '51210' => ['n' => 'Freight air transport', 's' => 'H'],
    '51220' => ['n' => 'Space transport', 's' => 'H'],
    '52101' => ['n' => 'Operation of warehousing and storage facilities for water transport activities', 's' => 'H'],
    '52102' => ['n' => 'Operation of warehousing and storage facilities for air transport activities', 's' => 'H'],
    '52103' => ['n' => 'Operation of warehousing and storage facilities for land transport activities', 's' => 'H'],
    '52211' => ['n' => 'Operation of rail freight terminals', 's' => 'H'],
    '52212' => ['n' => 'Operation of rail passenger facilities at railway stations', 's' => 'H'],
    '52213' => ['n' => 'Operation of bus and coach passenger facilities at bus and coach stations', 's' => 'H'],
    '52219' => ['n' => 'Other service activities incidental to land transportation, n.e.c.', 's' => 'H'],
    '52220' => ['n' => 'Service activities incidental to water transportation', 's' => 'H'],
    '52230' => ['n' => 'Service activities incidental to air transportation', 's' => 'H'],
    '52241' => ['n' => 'Cargo handling for water transport activities', 's' => 'H'],
    '52242' => ['n' => 'Cargo handling for air transport activities', 's' => 'H'],
    '52243' => ['n' => 'Cargo handling for land transport activities', 's' => 'H'],
    '52290' => ['n' => 'Other transportation support activities', 's' => 'H'],
    '53100' => ['n' => 'Postal activities under universal service obligation', 's' => 'H'],
    '53201' => ['n' => 'Licensed carriers', 's' => 'H'],
    '53202' => ['n' => 'Unlicensed carriers', 's' => 'H'],
    '55100' => ['n' => 'Hotels and similar accommodation', 's' => 'I'],
    '55201' => ['n' => 'Holiday centres and villages', 's' => 'I'],
    '55202' => ['n' => 'Youth hostels', 's' => 'I'],
    '55209' => ['n' => 'Other holiday and other collective accommodation', 's' => 'I'],
    '55300' => ['n' => 'Recreational vehicle parks, trailer parks and camping grounds', 's' => 'I'],
    '55900' => ['n' => 'Other accommodation', 's' => 'I'],
    '56101' => ['n' => 'Licenced restaurants', 's' => 'I'],
    '56102' => ['n' => 'Unlicenced restaurants and cafes', 's' => 'I'],
    '56103' => ['n' => 'Take-away food shops and mobile food stands', 's' => 'I'],
    '56210' => ['n' => 'Event catering activities', 's' => 'I'],
    '56290' => ['n' => 'Other food services', 's' => 'I'],
    '56301' => ['n' => 'Licenced clubs', 's' => 'I'],
    '56302' => ['n' => 'Public houses and bars', 's' => 'I'],
    '58110' => ['n' => 'Book publishing', 's' => 'J'],
    '58120' => ['n' => 'Publishing of directories and mailing lists', 's' => 'J'],
    '58130' => ['n' => 'Publishing of newspapers', 's' => 'J'],
    '58141' => ['n' => 'Publishing of learned journals', 's' => 'J'],
    '58142' => ['n' => 'Publishing of consumer and business journals and periodicals', 's' => 'J'],
    '58190' => ['n' => 'Other publishing activities', 's' => 'J'],
    '58210' => ['n' => 'Publishing of computer games', 's' => 'J'],
    '58290' => ['n' => 'Other software publishing', 's' => 'J'],
    '59111' => ['n' => 'Motion picture production activities', 's' => 'J'],
    '59112' => ['n' => 'Video production activities', 's' => 'J'],
    '59113' => ['n' => 'Television programme production activities', 's' => 'J'],
    '59120' => ['n' => 'Motion picture, video and television programme post- production activities', 's' => 'J'],
    '59131' => ['n' => 'Motion picture distribution activities', 's' => 'J'],
    '59132' => ['n' => 'Video distribution activities', 's' => 'J'],
    '59133' => ['n' => 'Television programme distribution activities', 's' => 'J'],
    '59140' => ['n' => 'Motion picture projection activities', 's' => 'J'],
    '59200' => ['n' => 'Sound recording and music publishing activities', 's' => 'J'],
    '60100' => ['n' => 'Radio broadcasting', 's' => 'J'],
    '60200' => ['n' => 'Television programming and broadcasting activities', 's' => 'J'],
    '61100' => ['n' => 'Wired telecommunications activities', 's' => 'J'],
    '61200' => ['n' => 'Wireless telecommunications activities', 's' => 'J'],
    '61300' => ['n' => 'Satellite telecommunications activities', 's' => 'J'],
    '61900' => ['n' => 'Other telecommunications activities', 's' => 'J'],
    '62011' => ['n' => 'Ready-made interactive leisure and entertainment software development', 's' => 'J'],
    '62012' => ['n' => 'Business and domestic software development', 's' => 'J'],
    '62020' => ['n' => 'Information technology consultancy activities', 's' => 'J'],
    '62030' => ['n' => 'Computer facilities management activities', 's' => 'J'],
    '62090' => ['n' => 'Other information technology service activities', 's' => 'J'],
    '63110' => ['n' => 'Data processing, hosting and related activities', 's' => 'J'],
    '63120' => ['n' => 'Web portals', 's' => 'J'],
    '63910' => ['n' => 'News agency activities', 's' => 'J'],
    '63990' => ['n' => 'Other information service activities n.e.c.', 's' => 'J'],
    '64110' => ['n' => 'Central banking', 's' => 'K'],
    '64191' => ['n' => 'Banks', 's' => 'K'],
    '64192' => ['n' => 'Building societies', 's' => 'K'],
    '64201' => ['n' => 'Activities of agricultural holding companies', 's' => 'K'],
    '64202' => ['n' => 'Activities of production holding companies', 's' => 'K'],
    '64203' => ['n' => 'Activities of construction holding companies', 's' => 'K'],
    '64204' => ['n' => 'Activities of distribution holding companies', 's' => 'K'],
    '64205' => ['n' => 'Activities of financial services holding companies', 's' => 'K'],
    '64209' => ['n' => 'Activities of other holding companies n.e.c.', 's' => 'K'],
    '64301' => ['n' => 'Activities of investment trusts', 's' => 'K'],
    '64302' => ['n' => 'Activities of unit trusts', 's' => 'K'],
    '64303' => ['n' => 'Activities of venture and development capital companies', 's' => 'K'],
    '64304' => ['n' => 'Activities of open-ended investment companies', 's' => 'K'],
    '64305' => ['n' => 'Activities of property unit trusts', 's' => 'K'],
    '64306' => ['n' => 'Activities of real estate investment trusts', 's' => 'K'],
    '64910' => ['n' => 'Financial leasing', 's' => 'K'],
    '64921' => ['n' => 'Credit granting by non-deposit taking finance houses and other specialist consumer credit grantors', 's' => 'K'],
    '64922' => ['n' => 'Activities of mortgage finance companies', 's' => 'K'],
    '64929' => ['n' => 'Other credit granting n.e.c.', 's' => 'K'],
    '64991' => ['n' => 'Security dealing on own account', 's' => 'K'],
    '64992' => ['n' => 'Factoring', 's' => 'K'],
    '64999' => ['n' => 'Financial intermediation not elsewhere classified', 's' => 'K'],
    '65110' => ['n' => 'Life insurance', 's' => 'K'],
    '65120' => ['n' => 'Non-life insurance', 's' => 'K'],
    '65201' => ['n' => 'Life reinsurance', 's' => 'K'],
    '65202' => ['n' => 'Non-life reinsurance', 's' => 'K'],
    '65300' => ['n' => 'Pension funding', 's' => 'K'],
    '66110' => ['n' => 'Administration of financial markets', 's' => 'K'],
    '66120' => ['n' => 'Security and commodity contracts dealing activities', 's' => 'K'],
    '66190' => ['n' => 'Activities auxiliary to financial intermediation n.e.c.', 's' => 'K'],
    '66210' => ['n' => 'Risk and damage evaluation', 's' => 'K'],
    '66220' => ['n' => 'Activities of insurance agents and brokers', 's' => 'K'],
    '66290' => ['n' => 'Other activities auxiliary to insurance and pension funding', 's' => 'K'],
    '66300' => ['n' => 'Fund management activities', 's' => 'K'],
    '68100' => ['n' => 'Buying and selling of own real estate', 's' => 'L'],
    '68201' => ['n' => 'Renting and operating of Housing Association real estate', 's' => 'L'],
    '68202' => ['n' => 'Letting and operating of conference and exhibition centres', 's' => 'L'],
    '68209' => ['n' => 'Other letting and operating of own or leased real estate', 's' => 'L'],
    '68310' => ['n' => 'Real estate agencies', 's' => 'L'],
    '68320' => ['n' => 'Management of real estate on a fee or contract basis', 's' => 'L'],
    '69101' => ['n' => 'Barristers at law', 's' => 'M'],
    '69102' => ['n' => 'Solicitors', 's' => 'M'],
    '69109' => ['n' => 'Activities of patent and copyright agents; other legal activities n.e.c.', 's' => 'M'],
    '69201' => ['n' => 'Accounting and auditing activities', 's' => 'M'],
    '69202' => ['n' => 'Bookkeeping activities', 's' => 'M'],
    '69203' => ['n' => 'Tax consultancy', 's' => 'M'],
    '70100' => ['n' => 'Activities of head offices', 's' => 'M'],
    '70210' => ['n' => 'Public relations and communications activities', 's' => 'M'],
    '70221' => ['n' => 'Financial management', 's' => 'M'],
    '70229' => ['n' => 'Management consultancy activities other than financial management', 's' => 'M'],
    '71111' => ['n' => 'Architectural activities', 's' => 'M'],
    '71112' => ['n' => 'Urban planning and landscape architectural activities', 's' => 'M'],
    '71121' => ['n' => 'Engineering design activities for industrial process and production', 's' => 'M'],
    '71122' => ['n' => 'Engineering related scientific and technical consulting activities', 's' => 'M'],
    '71129' => ['n' => 'Other engineering activities', 's' => 'M'],
    '71200' => ['n' => 'Technical testing and analysis', 's' => 'M'],
    '72110' => ['n' => 'Research and experimental development on biotechnology', 's' => 'M'],
    '72190' => ['n' => 'Other research and experimental development on natural sciences and engineering', 's' => 'M'],
    '72200' => ['n' => 'Research and experimental development on social sciences and humanities', 's' => 'M'],
    '73110' => ['n' => 'Advertising agencies', 's' => 'M'],
    '73120' => ['n' => 'Media representation services', 's' => 'M'],
    '73200' => ['n' => 'Market research and public opinion polling', 's' => 'M'],
    '74100' => ['n' => 'specialised design activities', 's' => 'M'],
    '74201' => ['n' => 'Portrait photographic activities', 's' => 'M'],
    '74202' => ['n' => 'Other specialist photography', 's' => 'M'],
    '74203' => ['n' => 'Film processing', 's' => 'M'],
    '74209' => ['n' => 'Photographic activities not elsewhere classified', 's' => 'M'],
    '74300' => ['n' => 'Translation and interpretation activities', 's' => 'M'],
    '74901' => ['n' => 'Environmental consulting activities', 's' => 'M'],
    '74902' => ['n' => 'Quantity surveying activities', 's' => 'M'],
    '74909' => ['n' => 'Other professional, scientific and technical activities n.e.c.', 's' => 'M'],
    '74990' => ['n' => 'Non-trading company non trading', 's' => 'M'],
    '75000' => ['n' => 'Veterinary activities', 's' => 'M'],
    '77110' => ['n' => 'Renting and leasing of cars and light motor vehicles', 's' => 'N'],
    '77120' => ['n' => 'Renting and leasing of trucks and other heavy vehicles', 's' => 'N'],
    '77210' => ['n' => 'Renting and leasing of recreational and sports goods', 's' => 'N'],
    '77220' => ['n' => 'Renting of video tapes and disks', 's' => 'N'],
    '77291' => ['n' => 'Renting and leasing of media entertainment equipment', 's' => 'N'],
    '77299' => ['n' => 'Renting and leasing of other personal and household goods', 's' => 'N'],
    '77310' => ['n' => 'Renting and leasing of agricultural machinery and equipment', 's' => 'N'],
    '77320' => ['n' => 'Renting and leasing of construction and civil engineering machinery and equipment', 's' => 'N'],
    '77330' => ['n' => 'Renting and leasing of office machinery and equipment (including computers)', 's' => 'N'],
    '77341' => ['n' => 'Renting and leasing of passenger water transport equipment', 's' => 'N'],
    '77342' => ['n' => 'Renting and leasing of freight water transport equipment', 's' => 'N'],
    '77351' => ['n' => 'Renting and leasing of air passenger transport equipment', 's' => 'N'],
    '77352' => ['n' => 'Renting and leasing of freight air transport equipment', 's' => 'N'],
    '77390' => ['n' => 'Renting and leasing of other machinery, equipment and tangible goods n.e.c.', 's' => 'N'],
    '77400' => ['n' => 'Leasing of intellectual property and similar products, except copyright works', 's' => 'N'],
    '78101' => ['n' => 'Motion picture, television and other theatrical casting activities', 's' => 'N'],
    '78109' => ['n' => 'Other activities of employment placement agencies', 's' => 'N'],
    '78200' => ['n' => 'Temporary employment agency activities', 's' => 'N'],
    '78300' => ['n' => 'Human resources provision and management of human resources functions', 's' => 'N'],
    '79110' => ['n' => 'Travel agency activities', 's' => 'N'],
    '79120' => ['n' => 'Tour operator activities', 's' => 'N'],
    '79901' => ['n' => 'Activities of tourist guides', 's' => 'N'],
    '79909' => ['n' => 'Other reservation service activities n.e.c.', 's' => 'N'],
    '80100' => ['n' => 'Private security activities', 's' => 'N'],
    '80200' => ['n' => 'Security systems service activities', 's' => 'N'],
    '80300' => ['n' => 'Investigation activities', 's' => 'N'],
    '81100' => ['n' => 'Combined facilities support activities', 's' => 'N'],
    '81210' => ['n' => 'General cleaning of buildings', 's' => 'N'],
    '81221' => ['n' => 'Window cleaning services', 's' => 'N'],
    '81222' => ['n' => 'Specialised cleaning services', 's' => 'N'],
    '81223' => ['n' => 'Furnace and chimney cleaning services', 's' => 'N'],
    '81229' => ['n' => 'Other building and industrial cleaning activities', 's' => 'N'],
    '81291' => ['n' => 'Disinfecting and exterminating services', 's' => 'N'],
    '81299' => ['n' => 'Other cleaning services', 's' => 'N'],
    '81300' => ['n' => 'Landscape service activities', 's' => 'N'],
    '82110' => ['n' => 'Combined office administrative service activities', 's' => 'N'],
    '82190' => ['n' => 'Photocopying, document preparation and other specialised office support activities', 's' => 'N'],
    '82200' => ['n' => 'Activities of call centres', 's' => 'N'],
    '82301' => ['n' => 'Activities of exhibition and fair organisers', 's' => 'N'],
    '82302' => ['n' => 'Activities of conference organisers', 's' => 'N'],
    '82911' => ['n' => 'Activities of collection agencies', 's' => 'N'],
    '82912' => ['n' => 'Activities of credit bureaus', 's' => 'N'],
    '82920' => ['n' => 'Packaging activities', 's' => 'N'],
    '82990' => ['n' => 'Other business support service activities n.e.c. security', 's' => 'N'],
    '84110' => ['n' => 'General public administration activities', 's' => 'O'],
    '84120' => ['n' => 'Regulation of health care, education, cultural and other social services, not incl. social security', 's' => 'O'],
    '84130' => ['n' => 'Regulation of and contribution to more efficient operation of businesses', 's' => 'O'],
    '84210' => ['n' => 'Foreign affairs', 's' => 'O'],
    '84220' => ['n' => 'Defence activities', 's' => 'O'],
    '84230' => ['n' => 'Justice and judicial activities', 's' => 'O'],
    '84240' => ['n' => 'Public order and safety activities', 's' => 'O'],
    '84250' => ['n' => 'Fire service activities', 's' => 'O'],
    '84300' => ['n' => 'Compulsory social security activities', 's' => 'O'],
    '85100' => ['n' => 'Pre-primary education', 's' => 'P'],
    '85200' => ['n' => 'Primary education', 's' => 'P'],
    '85310' => ['n' => 'General secondary education', 's' => 'P'],
    '85320' => ['n' => 'Technical and vocational secondary education', 's' => 'P'],
    '85410' => ['n' => 'Post-secondary non-tertiary education', 's' => 'P'],
    '85421' => ['n' => 'First-degree level higher education', 's' => 'P'],
    '85422' => ['n' => 'Post-graduate level higher education', 's' => 'P'],
    '85510' => ['n' => 'Sports and recreation education', 's' => 'P'],
    '85520' => ['n' => 'Cultural education', 's' => 'P'],
    '85530' => ['n' => 'Driving school activities', 's' => 'P'],
    '85590' => ['n' => 'Other education n.e.c.', 's' => 'P'],
    '85600' => ['n' => 'Educational support services', 's' => 'P'],
    '86101' => ['n' => 'Hospital activities', 's' => 'Q'],
    '86102' => ['n' => 'Medical nursing home activities', 's' => 'Q'],
    '86210' => ['n' => 'General medical practice activities', 's' => 'Q'],
    '86220' => ['n' => 'Specialists medical practice activities', 's' => 'Q'],
    '86230' => ['n' => 'Dental practice activities', 's' => 'Q'],
    '86900' => ['n' => 'Other human health activities', 's' => 'Q'],
    '87100' => ['n' => 'Residential nursing care facilities', 's' => 'Q'],
    '87200' => ['n' => 'Residential care activities for learning difficulties, mental health and substance abuse', 's' => 'Q'],
    '87300' => ['n' => 'Residential care activities for the elderly and disabled', 's' => 'Q'],
    '87900' => ['n' => 'Other residential care activities n.e.c.', 's' => 'Q'],
    '88100' => ['n' => 'Social work activities without accommodation for the elderly and disabled', 's' => 'Q'],
    '88910' => ['n' => 'Child day-care activities', 's' => 'Q'],
    '88990' => ['n' => 'Other social work activities without accommodation n.e.c.', 's' => 'Q'],
    '90010' => ['n' => 'Performing arts', 's' => 'R'],
    '90020' => ['n' => 'Support activities to performing arts', 's' => 'R'],
    '90030' => ['n' => 'Artistic creation', 's' => 'R'],
    '90040' => ['n' => 'Operation of arts facilities', 's' => 'R'],
    '91011' => ['n' => 'Library activities', 's' => 'R'],
    '91012' => ['n' => 'Archives activities', 's' => 'R'],
    '91020' => ['n' => 'Museums activities', 's' => 'R'],
    '91030' => ['n' => 'Operation of historical sites and buildings and similar visitor attractions', 's' => 'R'],
    '91040' => ['n' => 'Botanical and zoological gardens and nature reserves activities', 's' => 'R'],
    '92000' => ['n' => 'Gambling and betting activities', 's' => 'R'],
    '93110' => ['n' => 'Operation of sports facilities', 's' => 'R'],
    '93120' => ['n' => 'Activities of sport clubs', 's' => 'R'],
    '93130' => ['n' => 'Fitness facilities', 's' => 'R'],
    '93191' => ['n' => 'Activities of racehorse owners', 's' => 'R'],
    '93199' => ['n' => 'Other sports activities', 's' => 'R'],
    '93210' => ['n' => 'Activities of amusement parks and theme parks', 's' => 'R'],
    '93290' => ['n' => 'Other amusement and recreation activities n.e.c.', 's' => 'R'],
    '94110' => ['n' => 'Activities of business and employers membership organisations', 's' => 'S'],
    '94120' => ['n' => 'Activities of professional membership organisations', 's' => 'S'],
    '94200' => ['n' => 'Activities of trade unions', 's' => 'S'],
    '94910' => ['n' => 'Activities of religious organisations', 's' => 'S'],
    '94920' => ['n' => 'Activities of political organisations', 's' => 'S'],
    '94990' => ['n' => 'Activities of other membership organisations n.e.c.', 's' => 'S'],
    '95110' => ['n' => 'Repair of computers and peripheral equipment', 's' => 'S'],
    '95120' => ['n' => 'Repair of communication equipment', 's' => 'S'],
    '95210' => ['n' => 'Repair of consumer electronics', 's' => 'S'],
    '95220' => ['n' => 'Repair of household appliances and home and garden equipment', 's' => 'S'],
    '95230' => ['n' => 'Repair of footwear and leather goods', 's' => 'S'],
    '95240' => ['n' => 'Repair of furniture and home furnishings', 's' => 'S'],
    '95250' => ['n' => 'Repair of watches, clocks and jewellery', 's' => 'S'],
    '95290' => ['n' => 'Repair of personal and household goods n.e.c.', 's' => 'S'],
    '96010' => ['n' => 'Washing and (dry-)cleaning of textile and fur products', 's' => 'S'],
    '96020' => ['n' => 'Hairdressing and other beauty treatment', 's' => 'S'],
    '96030' => ['n' => 'Funeral and related activities', 's' => 'S'],
    '96040' => ['n' => 'Physical well-being activities', 's' => 'S'],
    '96090' => ['n' => 'Other service activities n.e.c. goods- and services-producing activities of households for own use', 's' => 'S'],
    '97000' => ['n' => 'Activities of households as employers of domestic personnel', 's' => 'T'],
    '98000' => ['n' => 'Residents property management', 's' => 'T'],
    '98100' => ['n' => 'Undifferentiated goods-producing activities of private households for own use', 's' => 'T'],
    '98200' => ['n' => 'Undifferentiated service-producing activities of private households for own use bodies', 's' => 'T'],
    '99000' => ['n' => 'Activities of extraterritorial organisations and bodies', 's' => 'U'],
    '99999' => ['n' => 'Dormant Company', 's' => 'U'],
];
