-- Migration 103: tenant_id on HR — recruiting, learning, performance.
-- Generated by cms/scripts/gen-tenant-id-migrations.php.
-- 21 table(s); pattern matches migration 100 (ADD NULL → backfill
-- 1 → NOT NULL + FK + index). See 100's header for design rationale.

ALTER TABLE `hr_jobs` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_jobs` SET    `tenant_id` = 1;
ALTER TABLE `hr_jobs` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_jobs_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_jobs_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_candidates` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_candidates` SET    `tenant_id` = 1;
ALTER TABLE `hr_candidates` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_candidates_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_candidates_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_applications` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_applications` SET    `tenant_id` = 1;
ALTER TABLE `hr_applications` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_applications_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_applications_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_application_notes` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_application_notes` SET    `tenant_id` = 1;
ALTER TABLE `hr_application_notes` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_application_notes_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_application_notes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_interviews` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_interviews` SET    `tenant_id` = 1;
ALTER TABLE `hr_interviews` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_interviews_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_interviews_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_skills` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_skills` SET    `tenant_id` = 1;
ALTER TABLE `hr_skills` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_skills_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_skills_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_goals` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_goals` SET    `tenant_id` = 1;
ALTER TABLE `hr_goals` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_goals_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_goals_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_courses` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_courses` SET    `tenant_id` = 1;
ALTER TABLE `hr_courses` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_courses_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_courses_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_course_assignments` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_course_assignments` SET    `tenant_id` = 1;
ALTER TABLE `hr_course_assignments` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_course_assignments_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_course_assignments_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_course_modules` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_course_modules` SET    `tenant_id` = 1;
ALTER TABLE `hr_course_modules` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_course_modules_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_course_modules_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_course_module_progress` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_course_module_progress` SET    `tenant_id` = 1;
ALTER TABLE `hr_course_module_progress` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_course_module_progress_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_course_module_progress_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_compliance_tasks` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_compliance_tasks` SET    `tenant_id` = 1;
ALTER TABLE `hr_compliance_tasks` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_compliance_tasks_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_compliance_tasks_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_compliance_task_notes` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_compliance_task_notes` SET    `tenant_id` = 1;
ALTER TABLE `hr_compliance_task_notes` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_compliance_task_notes_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_compliance_task_notes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_pulse_surveys` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_pulse_surveys` SET    `tenant_id` = 1;
ALTER TABLE `hr_pulse_surveys` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_pulse_surveys_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_pulse_surveys_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_pulse_responses` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_pulse_responses` SET    `tenant_id` = 1;
ALTER TABLE `hr_pulse_responses` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_pulse_responses_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_pulse_responses_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_reviews` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_reviews` SET    `tenant_id` = 1;
ALTER TABLE `hr_reviews` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_reviews_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_reviews_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_review_cycles` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_review_cycles` SET    `tenant_id` = 1;
ALTER TABLE `hr_review_cycles` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_review_cycles_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_review_cycles_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_succession_plans` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_succession_plans` SET    `tenant_id` = 1;
ALTER TABLE `hr_succession_plans` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_succession_plans_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_succession_plans_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_succession_plan_notes` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_succession_plan_notes` SET    `tenant_id` = 1;
ALTER TABLE `hr_succession_plan_notes` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_succession_plan_notes_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_succession_plan_notes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_succession_candidates` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_succession_candidates` SET    `tenant_id` = 1;
ALTER TABLE `hr_succession_candidates` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_succession_candidates_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_succession_candidates_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `hr_succession_candidate_notes` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `hr_succession_candidate_notes` SET    `tenant_id` = 1;
ALTER TABLE `hr_succession_candidate_notes` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_hr_succession_candidate_notes_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_hr_succession_candidate_notes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

