-- Migration 105: tenant_id on Recruitment + audience-specific document tables.
-- Generated by cms/scripts/gen-tenant-id-migrations.php.
-- 10 table(s); pattern matches migration 100 (ADD NULL → backfill
-- 1 → NOT NULL + FK + index). See 100's header for design rationale.

ALTER TABLE `recruitment_candidates` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_candidates` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_candidates` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_candidates_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_candidates_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_candidate_documents` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_candidate_documents` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_candidate_documents` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_candidate_documents_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_candidate_documents_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_candidate_notes` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_candidate_notes` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_candidate_notes` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_candidate_notes_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_candidate_notes_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_doc_groups` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_doc_groups` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_doc_groups` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_doc_groups_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_doc_groups_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_doc_types` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_doc_types` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_doc_types` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_doc_types_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_doc_types_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_placements` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_placements` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_placements` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_placements_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_placements_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_roles` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_roles` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_roles` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_roles_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_roles_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `recruitment_skills` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `recruitment_skills` SET    `tenant_id` = 1;
ALTER TABLE `recruitment_skills` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_recruitment_skills_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_recruitment_skills_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `candidate_documents` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `candidate_documents` SET    `tenant_id` = 1;
ALTER TABLE `candidate_documents` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_candidate_documents_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_candidate_documents_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `applicant_documents` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `applicant_documents` SET    `tenant_id` = 1;
ALTER TABLE `applicant_documents` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_applicant_documents_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_applicant_documents_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

