-- Migration 107: tenant_id on Misc — newsletter, billing, contract types, AI models.
-- Generated by cms/scripts/gen-tenant-id-migrations.php.
-- 7 table(s); pattern matches migration 100 (ADD NULL → backfill
-- 1 → NOT NULL + FK + index). See 100's header for design rationale.

ALTER TABLE `newsletter_campaigns` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `newsletter_campaigns` SET    `tenant_id` = 1;
ALTER TABLE `newsletter_campaigns` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_newsletter_campaigns_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_newsletter_campaigns_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `newsletter_recipients` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `newsletter_recipients` SET    `tenant_id` = 1;
ALTER TABLE `newsletter_recipients` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_newsletter_recipients_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_newsletter_recipients_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `newsletter_suppressions` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `newsletter_suppressions` SET    `tenant_id` = 1;
ALTER TABLE `newsletter_suppressions` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_newsletter_suppressions_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_newsletter_suppressions_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `invoices` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `invoices` SET    `tenant_id` = 1;
ALTER TABLE `invoices` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_invoices_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_invoices_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `invoice_lines` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `invoice_lines` SET    `tenant_id` = 1;
ALTER TABLE `invoice_lines` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_invoice_lines_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_invoice_lines_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `contract_types` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `contract_types` SET    `tenant_id` = 1;
ALTER TABLE `contract_types` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_contract_types_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_contract_types_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

ALTER TABLE `ai_models` ADD COLUMN `tenant_id` INT UNSIGNED NULL AFTER `id`;
UPDATE      `ai_models` SET    `tenant_id` = 1;
ALTER TABLE `ai_models` MODIFY `tenant_id` INT UNSIGNED NOT NULL,
                   ADD KEY `idx_ai_models_tenant` (`tenant_id`),
                   ADD CONSTRAINT `fk_ai_models_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants`(`id`);

