<?php
declare(strict_types=1);

use BRS\Db;
use BRS\Json;
use BRS\NotificationDispatcher;
use BRS\Tenant;

/*
 * Public feedback portal (no auth — token in URL).
 *
 *   GET  /api/public/feedback/:token             render the form
 *   POST /api/public/feedback/:token             submit answers
 *
 * Optional query string on either method:
 *   ?client=N   tag the submission against a CRM client
 *   ?lead=N     tag it against a lead
 *
 * The tenant is resolved off the form row itself (the token is global-
 * unique across tenants), so we override the auto-scope and look the
 * form up directly.
 */
return function (string $method, array $segs): void {
    Tenant::setForPublic();
    // Tokens are 40 hex chars. Accept either case so tokens seeded via
    // MySQL HEX() (uppercase) or generated by PHP bin2hex() (lowercase)
    // both resolve — the DB comparison is case-insensitive under utf8mb4
    // anyway; the regex was the strict gate.
    $token = strtolower((string)($segs[2] ?? ''));
    if (!preg_match('/^[a-f0-9]{40}$/', $token)) Json::fail('Invalid feedback link', 400);

    // Public form lookup — bypass tenant scoping since the token is the
    // access control. Once we have the form, set tenant context off it.
    $pdo = Db::pdo();
    $sel = $pdo->prepare('SELECT * FROM feedback_forms WHERE public_token = ? LIMIT 1');
    $sel->execute([$token]);
    $form = $sel->fetch();
    if (!$form)                Json::fail('Feedback form not found', 404);
    if (!$form['is_published']) Json::fail('Feedback form not published', 404);

    Tenant::overrideTo((int)$form['tenant_id']);
    $pdo = Db::tpdo();

    // Attribution — the canonical URL param is ?id=cN / ?id=lN / ?id=0.
    // Prefix picks the entity: 'c' → client, 'l' → lead, '0' or empty
    // → public/anonymous. Legacy ?client=/?lead= params are respected as
    // a fallback so links generated before the switch keep working.
    $clientId = null;
    $leadId   = null;
    if (isset($_GET['id']) && $_GET['id'] !== '') {
        $raw = trim((string)$_GET['id']);
        if ($raw !== '0') {
            $prefix = strtolower(substr($raw, 0, 1));
            $num    = (int)substr($raw, 1);
            if ($num > 0) {
                if ($prefix === 'c')      $clientId = $num;
                elseif ($prefix === 'l')  $leadId   = $num;
            }
        }
    } else {
        // Legacy fallback — kept so pre-switchover shared links still
        // resolve. Remove after any external caches expire.
        if (!empty($_GET['client'])) $clientId = (int)$_GET['client'];
        if (!empty($_GET['lead']))   $leadId   = (int)$_GET['lead'];
    }

    // Questions for both GET (render) and POST (validate)
    $qStmt = $pdo->prepare('SELECT * FROM feedback_questions WHERE form_id = ? ORDER BY sort_order, id');
    $qStmt->execute([$form['id']]);
    $questions = $qStmt->fetchAll();
    foreach ($questions as &$q) {
        $q['options'] = $q['options_json'] ? (json_decode($q['options_json'], true) ?: []) : [];
        unset($q['options_json']);
    }
    unset($q);

    if ($method === 'GET') {
        Json::send([
            'form' => [
                'id'                => (int)$form['id'],
                'kind'              => $form['kind'],
                'title'             => $form['title'],
                'description'       => $form['description'],
                'intro_html'        => $form['intro_html'],
                'submit_label'      => $form['submit_label'],
                'thank_you_message' => $form['thank_you_message'],
            ],
            'questions' => $questions,
            'context'   => [
                'client_id' => $clientId,
                'lead_id'   => $leadId,
            ],
        ]);
    }

    if ($method === 'POST') {
        $body    = Json::readBody();
        $answers = is_array($body['answers'] ?? null) ? $body['answers'] : [];

        // Build a quick lookup so we can validate required-ness
        $byId = [];
        foreach ($questions as $q) { $byId[(int)$q['id']] = $q; }

        // Validate required
        $present = [];
        foreach ($answers as $a) {
            $qid = (int)($a['question_id'] ?? 0);
            if (!$qid) continue;
            $present[$qid] = $a['value'] ?? null;
        }
        foreach ($questions as $q) {
            if (!empty($q['is_required'])) {
                $v = $present[(int)$q['id']] ?? null;
                if ($v === null || $v === '' || (is_array($v) && !$v)) {
                    Json::fail('Required answer missing: ' . $q['label'], 422);
                }
            }
        }

        $pdo->beginTransaction();
        try {
            $insR = $pdo->prepare(
                'INSERT INTO feedback_responses (form_id, client_id, lead_id, ip_address)
                 VALUES (?, ?, ?, ?)'
            );
            $insR->execute([
                $form['id'],
                $clientId,
                $leadId,
                $_SERVER['REMOTE_ADDR'] ?? null,
            ]);
            $responseId = (int)$pdo->lastInsertId();

            $insA = $pdo->prepare(
                'INSERT INTO feedback_answers (response_id, question_id, value)
                 VALUES (?, ?, ?)'
            );
            foreach ($answers as $a) {
                $qid = (int)($a['question_id'] ?? 0);
                if (!isset($byId[$qid])) continue;
                $value = $a['value'] ?? null;
                if (is_array($value)) $value = json_encode($value, JSON_UNESCAPED_UNICODE);
                $insA->execute([$responseId, $qid, $value === null ? null : (string)$value]);
            }

            $pdo->commit();
        } catch (\Throwable $e) {
            $pdo->rollBack();
            error_log('[public-feedback] submit failed: ' . $e->getMessage());
            Json::fail('Could not submit feedback', 500);
        }

        NotificationDispatcher::fire('crm.feedback.response', [
            'title'    => 'Feedback response — ' . ($form['title'] ?? 'form'),
            'body'     => null,
            'link_url' => '/admin/feedback/' . $form['id'],
        ]);

        Json::send([
            'ok' => true,
            'thank_you_message' => $form['thank_you_message'] ?: 'Thanks — your feedback has been received.',
        ], 201);
    }

    Json::fail('Method not allowed', 405);
};
